### Create New Course
POST http://localhost:8080/course/ HTTP/1.1 
content-type: application/json

{
"id" : 3, "courseName" : "gjdidld", "facultyName" : "vjnjkk" , "startDate" : "2023-08-12", "endDate" :"2023-10-04", "material" : "https://www.w3schools.com/js/", "recording" : "https://meet.google.com/woi-gjix-jsx"
}

### Get all Course
GET  http://localhost:8080/course/ HTTP/1.1 


### Delete Course By Id 
DELETE http://localhost:8080/course/1

### Get Course By Id 
GET http://localhost:8080/course/19


### Update Course

PUT http://localhost:8080/course/ HTTP/1.1 
content-type: application/json

{
    "id": 3,  "courseName" : "music", "facultyName" : "jasmine" , "startDate" : "2023-04-10", "endDate" :"2023-06-05", "material" : "https://www.w3schools.com/js/", "recording" : "https://meet.google.com/woi-gjix-jsx"
}

### Get Course By Name 
GET http://localhost:8080/course/name?courseName=dvheg
