### Login
POST http://localhost:8080/users/login HTTP/1.1 
content-type: application/json

{
    "email" : "fry@gmail.com", "password": "ttydgky"
}

### Register 
POST  http://localhost:8080/users/register HTTP/1.1 
content-type: application/json

{
    "name" :"gfjk", "email" : "fry@gmail.com", "password": "ttydgky", "role":"faculty"
}

