### Login
POST http://localhost:8080/users/login HTTP/1.1 
content-type: application/json

{
    "email" : "abcdefg@gmail.com", "password": "abcdeg"
}

### Register 
POST  http://localhost:8080/users/register HTTP/1.1 
content-type: application/json

{
    
     "name" :"abcdefg", "email" : "abcdefg@gmail.com", "password": "abcdeg", "role":"faculty"
    
}

