### Create New Notification
POST http://localhost:8080/notification/ HTTP/1.1 
content-type: application/json

{
"id" : 71, "date" : "2023-08-12", "notification" :"dhkvvk sdjkjok sdkskd "
}

### Get all Notifications
GET  http://localhost:8080/notification/ HTTP/1.1 


### Delete Notification By Id 
DELETE http://localhost:8080/notification/71

### Get Notification By Id 
GET http://localhost:8080/notification/19


### Update Notification

PUT http://localhost:8080/notification/ HTTP/1.1 
content-type: application/json

{
    "id": 70,  "date" : "2023-08-30", "notification" :"fghkjlk aaaaaaa guyiui "
}